script: bash ./deploy.sh
language: node_js
node_js:
- '5'
env:
  global:
  - GH_REF: github.com/pyrocms/branding.git
  - secure: WKFTr6Om9Ej4NcqPGpvAWs/HiGMNQZaeTEPuVPsNp8bjugSoJUJo0w/GTAJ80cpQrhxSKamTIPaglB0rYugkeak7Se8MmUODLczu7v2SefTzB1kU94Vw/MB+274JzwhyYfh3JZIiiVoji4fF7jMeINh9nWWzwPKhRy7gqcuB93MiZf8Iqj5vQylvPZ8I4uL5086ySGjlTrljbVKTsVaQSI0UnFzePYVleI5ExNA12Y3rWlyoNcZCFOne7LZermtiv1DBFkI06AcN1Q4Xc4GXq84yXG8cZ/jpWUhM+qxnjFiJxMfk7ddWjwcOldirqh2NnFJTrcAHMciVL1+jmzHrUeMvCx58w7HDyrJFT4/VY68SlwpoeuLijqaHI0qIR8vH1NuWBUDLnZJjEVT0UqGzlXDIjACC+IlsXtuKb7TGDSe/4WDCnKO7CdB79yC2ohfCaVPcPPPfmmQhqXUyhF8f8C2zBgnWP/GavV0v7SBK7Nr6FPjONUrCewF2rSRu1GFiybDT/SxPmfCGwuP30NAHT8YOEM/ia+XiMyy7Dxc0bUtuBVGOqQQhKxhh8rsahTt6GVWXi0BtxJfwo5YKVaWvvU3LiR3oK4gm4+8zgDe0iszehP2EeOiP7+2tILNgbRKSk/dbn4rkv5prLY+dZIm1jXAItqc3Kf00NEfmkJhqXVg=
